<?php
echo 'Show PHTML';



$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');

$collection = $productCollection->create()
            ->addAttributeToSelect('sku')
            ->load();


	//create a file
	$filename = "export_".date("Y.m.d").".csv";
	$csv_file = fopen('php://output', 'w');
	
	header('Content-type: application/csv');
	header('Content-Disposition: attachment; filename="'.$filename.'"');

	// The column headings of your .csv file
	$header_row = array("SKU");
	fputcsv($csv_file,$header_row,',','"');

foreach ($collection as $product){
$product_sku  =  $product->getSku();
$row = array($product_sku);
fputcsv($csv_file,$row,',','"');
} 

fclose($csv_file);

?>

<style>
header.page-header, .widget.block.block-static-block, .sections.nav-sections, .breadcrumbs, .promo_container, footer.page-footer, .footer-center-container, small.copyright { display: none;}

</style>