<style>
/* Style the tab */
.tab {
    overflow: hidden;
    border: 0;
    background-color: transparent;
}
/* Style the buttons inside the tab */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
  font-size: 17px;
  background: #f1f1f1;
  text-transform: uppercase;
  margin-right: 4px;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
    background-color: #333;
    color: #fff;
    text-transform: uppercase;
}
.catalog-product-view .tab { border-bottom: 5px solid #333;}

/* Style the tab content */
.tabcontent {
    display: none;
    padding: 0;
    border: 0;
    border-top: none;
    margin-top: -11px;
}/*
.widget.block.block-static-block .custom-slider{
	position : absolute; z-index : -1; opacity: 0;
}
.widget.block.block-static-block .custom_slider_1{
	position : relative; z-index : 1; opacity: 1;
}*/
</style>
<div class="tab">
  <button id="tab1" class="tablinks active" onclick="tabsNew('tab1', 1)">New Products</button>
  <button id="tab2" class="tablinks" onclick="tabsNew('tab2', 2)">Best Sellers</button>
  <button id="tab3" class="tablinks" onclick="tabsNew('tab3', 3)">Special offers</button>
</div>

<script>''

function tabsNew(tab, index){
    
    for(var i = 1; i<4; i++){
        document.getElementById('tab'+i).className='tablinks';
        document.getElementsByClassName('custom-slider custom_slider_'+i)[0].style.position="absolute";
        document.getElementsByClassName('custom-slider custom_slider_'+i)[0].style.zIndex="-1";
        document.getElementsByClassName('custom-slider custom_slider_'+i)[0].style.opacity="0";
    }
    document.getElementById(tab).className='tablinks active';
    document.getElementsByClassName('custom-slider custom_slider_'+index)[0].style.position="relative";
    document.getElementsByClassName('custom-slider custom_slider_'+index)[0].style.zIndex="1";
    document.getElementsByClassName('custom-slider custom_slider_'+index)[0].style.opacity="1";
}

</script>