<?php
/**
 * @category Mageants AdvanceReview
 * @package Mageants_AdvanceReview
 * @copyright Copyright (c) 2018 Mageants
 * @author Mageants Team <support@mageants.com>
 */
$blockObj= $block->getLayout()->createBlock('Mageants\AdvanceReview\Block\Review');
if($blockObj->isEnableAdvanceReview())
{
    if($blockObj->getAllowGroups())
    {
        if($blockObj->getOnlyPurchaser())
        {
        ?>
            <div class="block review-add">
                <div class="block-title"><strong><?php  echo __('Write Your Own Review') ?></strong></div>
            <div class="block-content">
            <?php if ($block->getAllowWriteReviewFlag()): ?>
            <form action="<?php  echo $block->getAction() ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'" enctype="multipart/form-data">
                <?php echo $block->getBlockHtml('formkey'); ?>
                <?php echo $block->getChildHtml('form_fields_before')?>
                <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
                    <legend class="legend review-legend"><span><?php echo __("You're reviewing:"); ?></span><strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend><br />
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                    <span id="input-message-box"></span>
                    <fieldset class="field required review-field-ratings">
                        <legend class="label"><span><?php echo __('Your Rating') ?><span></legend><br/>
                        <div class="control">
                            <div class="nested" id="product-review-table">
                                <?php foreach ($block->getRatings() as $_rating): ?>
                                    <div class="field choice review-field-rating">
                                        <label class="label" id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                        <div class="control review-control-vote">
                                        <?php $options = $_rating->getOptions();?>
                                        <?php $iterator = 1; foreach ($options as $_option): ?>
                                            <input
                                                type="radio"
                                                name="ratings[<?php echo $_rating->getId() ?>]"
                                                id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>"
                                                value="<?php echo $_option->getId() ?>"
                                                class="radio"
                                                data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                                aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>_label" />
                                            <label
                                                class="rating-<?php echo $iterator; ?>"
                                                for="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>"
                                                title="<?php echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                                id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>_label">
                                                <span><?php echo __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                            </label>
                                        <?php $iterator++; ?>
                                        <?php endforeach; ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        </div>
                    </fieldset>
                <?php endif ?>
                <input type="hidden" name="verified_purchase" value="<?php if($blockObj->getVerifiedPurchase()){ echo "1"; }else{ echo "0"; }  ?>">
                    <div class="field review-field-nickname">
                        <label for="file" class="label"><span><?php echo __('Add a photo or video') ?></span></label>
                        <div class="control" id="control">
                            <input type="file" name="image_video[0]" id="img_video_field" class="input-text" data-bind="value: review().image" accept="image/*, video/*" />
                            <button type="button" id="add" onclick="addField(this)"><span>+</span></button>
                            <button type="button" id="del" onclick="delField()">x</button>
                        </div>
                    </div>
                    <div class="field review-field-nickname required">
                        <label for="nickname_field" class="label"><span><?php echo __('Nickname') ?></span></label>
                        <div class="control">
                            <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                        </div>
                    </div>
                    <div class="field review-field-summary required">
                        <label for="summary_field" class="label"><span><?php echo __('Summary') ?></span></label>
                        <div class="control">
                            <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                        </div>
                    </div>
                    <div class="field review-field-text required">
                        <label for="review_field" class="label"><span><?php echo __('Review') ?></span></label>
                        <div class="control">
                            <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar review-form-actions">
                    <div class="primary actions-primary">
                        <button type="submit" class="action submit primary"><span><?php echo __('Submit Review') ?></span></button>
                    </div>
                </div>
            </form>
            <script type="text/x-magento-init">
            {
                "[data-role=product-review-form]": {
                    "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
                },
                "#review-form": {
                    "Magento_Review/js/error-placement": {}
                }
            }
            </script>
            <script type="text/javascript">
                var i = 0;
                function addField(img) {
                    if(i < 9){
                        i++;
                        img = document.getElementById('control');
                        var br = document.createElement("br");
                        br.id = "br_" + i;
                        
                        var input = document.createElement("input");
                        input.type = "file";
                        input.name = "image_video["+i+"]";
                        input.id = "img_video_" + i;
                        input.class = "input-text";
                        input.accept = "image/*, video/*";
                        img.appendChild(input);
                        img.appendChild(br);
                    }
                }
                function delField() {
                    if (document.getElementById("img_video_1") == null) {
                        document.getElementById("img_video_field").value = "";
                    }
                    if (i > 0) {
                        document.getElementById("img_video_" + i).remove();
                        document.getElementById("br_" + i).remove();
                        i--;
                    }
                }
            </script>
            <?php else: ?>
                <div class="message info notlogged" id="review-form">
                    <div>
                        <?php echo __('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
                    </div>
                </div>
            <?php endif ?>
            </div>
            </div>
        <?php
        }
    }
}
?>