<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Template */
//phpcs:disable Magento2.Files.LineLength.MaxExceeded

$parentBlock = $block->getParentBlock();
$track = $block->getData('track');
$email = $block->getData('storeSupportEmail');
$fields = [
    'Status' => 'getStatus',
    'Signed by' => 'getSignedby',
    'Delivered to' => 'getDeliveryLocation',
    'Shipped or billed on' => 'getShippedDate',
    'Service Type' => 'getService',
    'Weight' => 'getWeight',
];
$number = is_object($track) ? $track->getTracking() : $track['number'];
?>
<table class="data table order tracking" id="tracking-table-popup-<?= $block->escapeHtml($number) ?>">
    <caption class="table-caption"><?= $block->escapeHtml(__('Order tracking')) ?></caption>
    <tbody>
    <?php if (is_object($track)) : ?>
        <tr>
            <th class="col label" scope="row"><?= $block->escapeHtml(__('Tracking Number:')) ?></th>
            <td class="col value"><?= $block->escapeHtml($number) ?></td>
        </tr>
        <?php if ($track->getCarrierTitle()) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Carrier:')) ?></th>
                <td class="col value"><?= $block->escapeHtml($track->getCarrierTitle()) ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($track->getErrorMessage()) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Error:')) ?></th>
                <td class="col error">
                    <?= $block->escapeHtml(__('Tracking information is currently not available. Please ')) ?>
                    <?php if ($parentBlock->getContactUsEnabled()) : ?>
                        <a href="<?= $block->escapeUrl($parentBlock->getContactUs()) ?>" target="_blank"
                           title="<?= $block->escapeHtml(__('contact us')) ?>">
                            <?= $block->escapeHtml(__('contact us')) ?>
                        </a>
                        <?= $block->escapeHtml(__(' for more information or ')) ?>
                    <?php endif; ?>
                    <?= $block->escapeHtml(__('email us at ')) ?>
                    <a href="mailto:<?= /* @noEscape */ $email ?>"><?= /* @noEscape */ $email ?></a>
                </td>
            </tr>
        <?php elseif ($track->getTrackSummary()) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Info:')) ?></th>
                <td class="col value"><?= $block->escapeHtml($track->getTrackSummary()) ?></td>
            </tr>
        <?php elseif ($track->getUrl()) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Track:')) ?></th>
                <td class="col value">
                    <a href="<?= $block->escapeUrl($track->getUrl()) ?>" target="_blank">
                        <?= $block->escapeUrl($track->getUrl()) ?>
                    </a>
                </td>
            </tr>
        <?php else : ?>
            <?php foreach ($fields as $title => $property) : ?>
                <?php if (!empty($track->$property())) : ?>
                    <tr>
                        <th class="col label" scope="row"><?= /* @noEscape */ $block->escapeHtml(__($title . ':')) ?></th>
                        <td class="col value"><?= $block->escapeHtml($track->$property()) ?></td>
                    </tr>
                <?php endif;?>
            <?php endforeach; ?>

            <?php if ($track->getDeliverydate()) : ?>
                <tr>
                    <th class="col label" scope="row"><?= $block->escapeHtml($parentBlock->getDeliveryDateTitle()->getTitle($track)) ?></th>
                    <td class="col value">
                        <?= /* @noEscape */ $parentBlock->formatDeliveryDateTime($track->getDeliverydate(), $track->getDeliverytime()) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endif; ?>
    <?php elseif (isset($track['title']) && isset($track['number']) && $track['number']) : ?>
        <?php /* if the tracking is custom value */ ?>
        <tr>
            <th class="col label" scope="row">
                <?= ($track['title'] ? $block->escapeHtml($track['title']) : $block->escapeHtml(__('N/A'))) ?>:
            </th>
            </br>
            <p><b>Please follow below instructions to track your order.</b></p>
            <p>1. Copy your tracking number by clicking on the button give below</p>
            <p>2. Click on the link next to the courier name. A website link will open. </p>
            <p>3. Paste the tracking number</p>
            <button id="copy-button">Copy Tracking Code</button>
            </br>
            <?php if ($track['title'] == 'Royal Mail ') { ?> 
            <td class="col value"><a href="https://www.royalmail.com/track-your-item#/"><?= (isset($track['number']) ? $block->escapeHtml($track['number']) : '') ?></a></td>
            <?php }elseif($track['title'] == 'Yodel '){ ?>
                <td class="col value"><a href="https://www.yodel.co.uk/track"><?= (isset($track['number']) ? $block->escapeHtml($track['number']) : '') ?></a></td>
            <?php }elseif($track['title'] == 'Parcelforce '){ ?>
                <td class="col value"><a href="https://www.parcelforce.com/track-trace?parcel_tracking_number=<?php echo $track['number']; ?>"><?= (isset($track['number']) ? $block->escapeHtml($track['number']) : '') ?></a></td>
            <?php }elseif($track['title'] == 'Hermes '){ ?>
                <td class="col value"><a href="https://www.evri.com/track-a-parcel"><?= (isset($track['number']) ? $block->escapeHtml($track['number']) : '') ?></a></td>
            <?php }else{ ?>
                <td class="col value"><?= (isset($track['number']) ? $block->escapeHtml($track['number']) : '') ?></td>
            <?php } ?>

        </tr>
    <?php endif; ?>
    </tbody>
</table>
<script>
require(['jquery', 'jquery/ui'], function($){
  $(document).ready( function() {
        $('#copy-button').click(function() {
            var textToCopy = $('.col.value').text();
            var tempTextarea = $('<textarea>');
            $('body').append(tempTextarea);
            tempTextarea.val(textToCopy).select();
            document.execCommand('copy');
            tempTextarea.remove();
        });
    });
});
</script>