<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
/**
 * @var \Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolverInterface|null $logoSizeResolver
 */
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span>
<a
    class="logo"
    href="<?= $block->escapeUrl($block->getUrl('')) ?>"
    title="<?= $block->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $logoWidth ? 'width="' . $block->escapeHtmlAttr($logoWidth) . '"' : '' ?>
            <?= $logoHeight ? 'height="' . $block->escapeHtmlAttr($logoHeight) . '"' : '' ?>
    />
</a>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
if ($request->getFullActionName() == 'cms_index_index') {
?>
<style>
    a,p,strong,span,button,H1,H2,H3,H4,H5,body,.promo_container ul li p {font-family: 'Roboto', sans-serif !important;}
    .elb-container-1 p, .footer.content .links a, .custom_slider_1 .product-item-details strong.product.name.product-item-name a, .footer.content .links li, .ftr-center a, small.copyright span {color: #777 !important;}

</style>

<?php
}

?>
<script type="text/javascript">
    require([
        "jquery"
    ], function ($) {
	jQuery(window).on('load', function() {
		  jQuery(".footer-center-container").insertAfter("footer.page-footer");
		  jQuery("ul.compare.wrapper").insertBefore(".block.block-search");
		  jQuery(".dz_share").insertAfter("div#tab-label-description");
		
       });	
		
    });
		
</script>

<script type="text/javascript">
    require([
        "jquery"
    ], function ($) {
		jQuery(window).on('load', function() {
			jQuery(".btn1").on("click",function(){
			jQuery(".btn1").addClass("dz_active");
			jQuery(".btn2").removeClass("dz_active");
			jQuery(".btn3").removeClass("dz_active");
			jQuery(".dz-best").addClass("dz_tabactive");
			jQuery(".dz-new").removeClass("dz_tabactive");
			jQuery(".dz-spacial").removeClass("dz_tabactive");
			jQuery(".dz_tabactive").css("transition-duration", "2s");
		});
		jQuery(".btn2").on("click",function(){
			jQuery(".btn1").removeClass("dz_active");
			jQuery(".btn2").addClass("dz_active");
			jQuery(".btn3").removeClass("dz_active");
			jQuery(".dz-best").removeClass("dz_tabactive");
			jQuery(".dz-new").addClass("dz_tabactive");
			jQuery(".dz-spacial").removeClass("dz_tabactive");
		});
		jQuery(".btn3").on("click",function(){
			jQuery(".btn1").removeClass("dz_active");
			jQuery(".btn2").removeClass("dz_active");
			jQuery(".btn3").addClass("dz_active");
			jQuery(".dz-best").removeClass("dz_tabactive");
			jQuery(".dz-new").removeClass("dz_tabactive");
			jQuery(".dz-spacial").addClass("dz_tabactive");
		});
		jQuery(".product-info-main .product-info-price .price-box.price-final_price").insertBefore(".box-tocart .fieldset");
		jQuery(".checkout-cart-index .cart-summary._sticky").insertAfter(".checkout-cart-index .cart-discount");
                //jQuery(".catalogsearch-result-index .energy-container").insertAfter(".catalogsearch-result-index .sidebar-additional");
                jQuery("#tab-label-description").off("click");
     });
	/*  document.getElementById("tab-label-description-title").onclick = function() {
     this.disabled = true;
    } */
		
   });
		
</script>
<style>

img.gallery-placeholder__image, .fotorama__stage__frame .fotorama__img {
    max-width: 300px;
    max-height: 300px;
}

[name='shippingAddress.city'] span:before {
    content: 'County / ';
}
.sidebar.sidebar-additional .block.paypal.acceptance {
    display: none;
}
.billing-address-form .step-title:after {content: ' Payment Card Address'; }
.checkout-index-index .all_page_cats {
    display: none;
}
/*div#product-review-container .review-ratings, div#product-review-container .avgrating , div#product-review-container .star { 
display: none;
}*/
 
.checkout-cart-index h1.page-title {
    width: 100%;
}
.opayo-payment-method-logo {  min-width: 275px;}

.catalogsearch-result-index .products.wrapper.grid.products-grid .product-item-inner {
    position: absolute;
    margin-left: -1px;
    border: none !important;
    padding-top: 0;
    height: auto;
    margin-top: -1px;
    min-height: 0;
    width: 92%;
    background: #ff6500 !important;
    border-bottom-left-radius: 4px !important;
    border-bottom-right-radius: 4px !important;
    box-shadow: none !important;
    border: 1px solid #ff6500 !important;
}

.catalogsearch-result-index  .product-item .tocart {
    background-color: transparent !important;
    border-color: transparent !important;padding: 0;
}

.product-item .product-item-info:hover .bss-quickview {
    max-width: 60px;
    top: 0;
    background: url(https://energylightbulbs.co.uk/pub/static/frontend/Energylights/Bulbs/en_GB/images/sprite.png) no-repeat;
    background-position: -481px -109px;
}
.product-item .product-item-info:hover .bss-quickview span {
    display: none;
}

p.base_img span.image_label {
    display: block;
}
.catalog-product-view .dz_share {top: -34px;}
.catalog-product-view .owl-dots {  display: none;}
.footer-top-right .contact-us ul li.tel span.icon:before {
    font-weight: 800 !important;
    color: #333;
    font-style: normal;
    text-decoration: inherit;
    font-size: 17px;
    padding-right: 0.5em;
    top: 10px;
    content: "\f095";
    font-family: FontAwesome;
}
.footer-top-right .contact-us ul li.email span.icon:before {
    font-weight: 800 !important;
    color: #333;
    font-style: normal;
    text-decoration: inherit;
    font-size: 17px;
    padding-right: 0.5em;
    content: "\f0e0";
    font-family: FontAwesome;
    margin-top: -10px;
    display: block;
}
.cms-index-index .dz-product-tab.clearfix .custom-slider{padding:5px 5px 20px !important}
.catalog-category-view .product-item .price-box {   margin: 0;}
.catalog-category-view .products.wrapper.grid.products-grid li.item.product.product-item {  padding: 0;}
.catalog-category-view .product-item-name { text-transform: capitalize !important;   padding: 0 15px;   line-height: 20px;} 

/*
span.price::after {
    margin-top: -4px;
    margin-left: 5px;
    font-weight: normal;
    font-family: Arial, sans-serif;
    font-size: 15px;
    color: #4b4b4b;
    text-transform: none;
    display: inline-block;
    vertical-align: middle;
    content: '(Incl. Vat)';
}*/
.checkout-cart-index button.action.update { display: inline-block; margin-left: 20px; }



.energy-container {
    margin: 0;
}

.energy-content a.energy_view {
    display: block;
    float: left;
    min-width: 100px;
    text-align: center;
}

.energy-content {
    display: inline-block;
    vertical-align: top;
    width: 100% !important;;
    padding: 7px 0 5px;
}
.energy-3.dz_container, .energy-2.dz_container, .energy-1.dz_container {    width: 100% !important; }
.energy-1.dz_container span, .energy-2.dz_container span, .energy-3.dz_container span {display: none;}
.energy-content h2 { font-size: 16px;}
.footer.content .footer-top-container .links {
    padding-right: 45px !important;
}

[name="shippingAddress.region"] span:before, [name="billingAddress.region"] span:before {
    content: 'County / ';
}
.newshow {
    display: none !important;
}
.payment-icon.sagepaysuite-payment-icon.opayo-payment-method-logo {
    background-size: contain;
    background-position: left;
}


.opayo-payment-method-logo {
    min-width: 350px; 
    position: relative;
}

.opayo-payment-method-logo:before {
    content: '';
    background: url(https://doo9vxlv0gkqf.cloudfront.net/media/checkoutpayment.jpg);
    right: 0;
    position: absolute;
    min-width: 217px;
    height: 40px;
    background-size: contain;
    background-repeat: no-repeat;
    bottom: 0;
}

.catalog-category-view h1#page-title-heading {
    font-size: 26px;
}

.sidebar.sidebar-additional {
    display: none;
}
</style>

<script type="text/javascript">
function roundAmount(theDecimal) {
	var s = "" + Math.round(theDecimal * 100) / 100
	var i = s.indexOf('.');
	if (i < 0) {
		return s + ".00";
	}
	var t = s.substring(0, i + 1) + s.substring(i + 1, i + 3);
	if (i + 2 == s.length) {
		t += "0";
	}
	return t;
}
function calcEnergy() {
    console.log('triger');
	if (document.getElementById("hours").value > 24){
		alert("24 hours a day is all we have!");
		return false;
	}
	
	document.getElementById("tariff").innerHTML = document.calc.energycost.value;
	document.getElementById("watts-energy-saving").innerHTML = document.calc.watt.value / 5;
	document.getElementById("annualcurrent").innerHTML = document.calc.watt.value;
	
	var yearlynormallamp = (document.calc.energycost.value * 0.01 * 365 * document.calc.use.value * document.calc.hours.value * document.calc.watt.value) / 1000;
	var yearlyenergysaving = (document.calc.energycost.value * 0.01 * 365 * document.calc.use.value * document.calc.hours.value * ((document.calc.watt.value)/5)) / 1000;
	var lifeenergysaving = ((((document.calc.watt.value * 0.001) - (document.calc.watt.value * 0.001 /5)) * 8000) * document.calc.energycost.value /100) * document.calc.use.value;
	
	document.getElementById("yearlynormallamp").innerHTML = roundAmount(yearlynormallamp,2);
	document.getElementById("yearlyenergysaving").innerHTML = roundAmount(yearlyenergysaving,2);
	document.getElementById("lifeenergysaving").innerHTML = roundAmount(lifeenergysaving,2);
	document.getElementById("total").innerHTML = roundAmount(yearlynormallamp-yearlyenergysaving,2);
}

</script>